# -*- coding: utf-8 -*-
"""excel파일을 DataFrame으로 만들기 부가설명 추가_포트폴리오.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1886b9KMg5dllNCIZ93gVf7X-VpCc_1re

# Excel 파일을 DataFrame으로 만들기

***5주차 수업 추가 정리***
"""

import numpy as np

data = np.random.rand(3,5)
data

import pandas as pd

pd.read_excel('2020-01.xlsx')

df = pd.read_excel('2020-01.xlsx' ,index_col='상품명')

df.head()

df.head(10)

df.tail()

df1 = df.nlargest(10, '판매건수')
df1

df1.plot()

df1.plot(kind='pie', y='판매건수')

df.nsmallest(10, '판매건수')

df.nsmallest(10, ['판매건수', '가격'])

df.sort_values?

df.sort_values('가격', ascending=False) [:100]

df.sort_values('가격', ascending=False) [100:200]

"""---"""